### ISSUE TITLE
Make it compatible with Laravel 10

### ISSUE THREAD

**Issue by kornatzky** [vormkracht10/laravel-seo-scanner#23]
Cannot be installed currently in Laravel 10 project.

**Comment by Baspa** [comment]
What error does it give? Please give us more information.. @kornatzky

**Comment by kornatzky** [comment]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires vormkracht10/laravel-seo-scanner * -> satisfiable by vormkracht10/laravel-seo-scanner[v1.0.0, v1.0.1, v1.1.0, v1.1.1].
    - vormkracht10/laravel-seo-scanner[v1.0.0, ..., v1.1.1] require illuminate/contracts ^9.0 -> found illuminate/contracts[v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require vormkracht10/laravel-seo-scanner:*" to figure out if any version is installable, or "composer require vormkracht10/laravel-seo-scanner:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by Baspa** [comment]
This will be fixed in #24  @kornatzky

**Comment by kornatzky** [comment]
Great. Thanks

**Comment by Baspa** [comment]
Fixed in the new release! Thanks for mentioning the issue.

**Comment by kornatzky** [comment]
Thanks. Waiting for it. Still not see in packagist. I guess it takes some time. Composer still tries to install 1.1.1

**Comment by Baspa** [comment]
I updated the package in packagist. Should install 1.2.0 now.

**Comment by kornatzky** [comment]
Indeed. Works. Thanks for the attention. 😀
